.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. uex_qt test_uex_qt
clean: FORCE
	$(MAKE) -C .. uex_qt_clean test_uex_qt_clean
check: FORCE
	$(MAKE) -C .. test_uex_qt_check
uex-qt uex-qt.exe: FORCE
	 $(MAKE) -C .. uex_qt
